In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('train.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [5]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
data.shape

(891, 12)

In [7]:
data.describe(include=[np.object])

Name   Sex    Ticket Cabin Embarked
count                    891   891       891   204      889
unique                   891     2       681   147        3
top     Elias, Mr. Joseph Jr  male  CA. 2343    G6        S
freq                       1   577         7     4      644

In [8]:
data.describe(include=[np.int64])

PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

In [9]:
print(data.isnull().any())

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool


In [10]:
print(data.Age.isna().sum())

177


In [11]:
print(data.Cabin.isna().sum())

687


In [12]:
print(data.Embarked.isna().sum())

2


In [13]:
print(data.Age.mean())

29.69911764705882


In [14]:
print(data.Age.median())

28.0


In [15]:
print(data.Age.std())

14.526497332334042


In [16]:
print(data.Age.describe())

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64


In [17]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [18]:
data.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [19]:
total=data.Sex.count()

In [20]:
percentage_women = (data['Sex'][data['Sex']=='female'].count()/total)*100

In [21]:
percentage_men = (data['Sex'][data['Sex']=='male'].count()/total)*100

In [22]:
print(percentage_women)

35.24130190796858


In [23]:
print(percentage_men)

64.75869809203144


In [24]:
pd.crosstab(data['Sex'],data['Survived'])

Survived    0    1
Sex               
female     81  233
male      468  109

In [25]:
male_survived = data['Sex'][(data['Sex']=='male')&(data['Survived']==0)].shape[0]

In [26]:
male_unsurvived = data['Sex'][(data['Sex']=='male')&(data['Survived']==1)].shape[0]

In [27]:
male_unsurvived

109

In [28]:
male_survived

468

In [29]:
female_survived = data['Sex'][(data['Sex']=='female')&(data['Survived']==1)].shape[0]

In [30]:
female_unsurvived = data['Sex'][(data['Sex']=='female')&(data['Survived']==0)].shape[0]

In [31]:
female_survived

233

In [32]:
female_unsurvived

81

In [33]:
survived_data = pd.DataFrame()

In [34]:
survived_data['survived']=[male_survived,female_survived]

In [35]:
survived_data

survived
0       468
1       233

In [36]:
survived_data.index =['mens data' ,'female data']

In [37]:
survived_data

survived
mens data         468
female data       233

In [38]:
survived_data['unsurvived']=[female_survived,female_unsurvived]

In [39]:
survived_data

survived  unsurvived
mens data         468         233
female data       233          81

In [40]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [41]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [42]:
miss_removed = data.dropna()
miss_removed.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [43]:
miss_removed.shape

(183, 12)

In [44]:
data.shape

(891, 12)

In [45]:
clear_data = data

In [46]:
clear_data.shape

(891, 12)

In [47]:
clear_data.Age = clear_data.Age.fillna(data.Age.mean())

In [48]:
clear_data.shape

(891, 12)

In [49]:
clear_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [50]:
data['Age'][data['Age']>65]

33     66.0
96     71.0
116    70.5
493    71.0
630    80.0
672    70.0
745    70.0
851    74.0
Name: Age, dtype: float64

In [51]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [52]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [53]:
training_data = data[['PassengerId' , 'Pclass','Age','Fare']]

In [54]:
training_data.isnull().sum()

PassengerId    0
Pclass         0
Age            0
Fare           0
dtype: int64

In [55]:
training_data.shape

(891, 4)

In [56]:
output_data =data['Survived']

In [57]:
output_data.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [58]:
output_data.shape[0]

891

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X,x_test,Y,y_test = train_test_split(training_data, output_data, test_size=0.4, random_state=42)

In [61]:
y_test.head()

709    1
439    0
840    0
720    1
39     1
Name: Survived, dtype: int64

In [62]:
x_test.head()

PassengerId  Pclass        Age     Fare
709          710       3  29.699118  15.2458
439          440       2  31.000000  10.5000
840          841       3  20.000000   7.9250
720          721       2   6.000000  33.0000
39            40       3  14.000000  11.2417

In [63]:
X.head()

PassengerId  Pclass   Age     Fare
570          571       2  62.0  10.5000
787          788       3   8.0  29.1250
74            75       3  32.0  56.4958
113          114       3  20.0   9.8250
635          636       2  28.0  13.0000

In [64]:
model.fit(X,Y)

c:\users\naveen\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [65]:
model.coef_

array([[-6.68384818e-05, -7.36073749e-01, -2.82851660e-02,
         5.20566362e-03]])

In [66]:
details = pd.DataFrame(model.coef_.T , index = training_data.columns , columns=['vlaues'])

In [67]:
details

vlaues
PassengerId -0.000067
Pclass      -0.736074
Age         -0.028285
Fare         0.005206

In [68]:
single_prediction = model.predict([[892,3,32.0,56.4958]])

In [69]:
single_prediction

array([0], dtype=int64)

In [70]:
training_prediction = model.predict(x_test)

In [71]:
training_prediction.shape[0]

357

In [72]:
training_prediction[0:10]

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1], dtype=int64)

In [73]:
from sklearn.metrics import accuracy_score

In [74]:
my_accuracy = accuracy_score(training_prediction, y_test)

In [75]:
my_accuracy

0.7226890756302521

# accuracy is 72.689

In [76]:
x_test.head()

PassengerId  Pclass        Age     Fare
709          710       3  29.699118  15.2458
439          440       2  31.000000  10.5000
840          841       3  20.000000   7.9250
720          721       2   6.000000  33.0000
39            40       3  14.000000  11.2417

In [77]:
x_test.head()

PassengerId  Pclass        Age     Fare
709          710       3  29.699118  15.2458
439          440       2  31.000000  10.5000
840          841       3  20.000000   7.9250
720          721       2   6.000000  33.0000
39            40       3  14.000000  11.2417

In [78]:
x_test.shape

(357, 4)

In [79]:
training_prediction.shape

(357,)

In [80]:
submission = pd.DataFrame({"passangerId":x_test['PassengerId'],'survived':training_prediction})

In [81]:
submission.head()

passangerId  survived
709          710         0
439          440         0
840          841         0
720          721         1
39            40         0

In [82]:
submission.to_csv("survived_data.csv")

In [100]:
from sklearn.metrics import mean_squared_error

In [85]:
from sklearn.neighbors import KNeighborsClassifier

In [86]:
model2 = KNeighborsClassifier()

In [87]:
model2.fit(X,Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [90]:
my_predict = model2.predict([[892,3,32.0,56.4958]])

In [91]:
my_predict

array([0], dtype=int64)

In [92]:
model2_predict = model2.predict(x_test)

In [93]:
model2_predict.shape

(357,)

In [97]:
model2_predict[0:15]

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [98]:
my_accuracy2 = accuracy_score(model2_predict,y_test)

In [99]:
my_accuracy2

0.6526610644257703

# accuracy of neighbour classifier is 65.266